package org.processmining.plugins.declareminer.enumtypes;

public enum MapTemplateConfiguration {
	DiscoverProvidedTemplatesAcrossAllActivitesInLog, StrengthenMap, DiscoverProvidedTemplatesAcrossActivitiesOnlyInTheMap
}
